import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { extendBaseTheme, Button, ChakraBaseProvider } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const theme = extendBaseTheme({
  components: {
    Button,
  },
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraBaseProvider theme={theme}>
          {children}
        </ChakraBaseProvider></body>
    </html>
  )
}
